language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  provider: heroku
  api_key:
    secure: HRNNitGt9facPms0xi239lBG4TwW3v6MwXPZjDxvWGmf8UAgYZtbFxgOeGuE8PlNerAStGUlPtxl70LHpbUglI+UElhy8ZNCSmVlU45yR5wZTP42SzTsu2YLab1W9W+gtGV7no3+lEi3ELM2AwWSM1N3GPB0v1i6MY/sMMVAT2hcVodlXtfaPBlkxayXm/6ou0W1f8Zn4JCUUF23uVMF1A5IakXALuH+ZErfP3usOpT3F8s+zDE7BMMeftnd8bi5OfxZFRgP4kRsdvg7YqkG9XZzyWYlJI6Tf8L4tTQfokMJzQ41DkCqoTg0mE8bn52oHlv3V7NbLPBcJKiOvbVLETyVbMNriZtWV6KBuEwyHinJCJOqDMcIZCzz9zTfrH1vz5wsRBV+PV9k5ddAVErNYIrSS4cUdG25uK1A1r/VlXffa02NqdOnJvZC1NKbM4nsuOEToweVFpeWuKYPRTXSHMgmFeIZ9dY1fOXXhk2jltQ9sLpFMQxRuKHapsjGqaxxVj6C9UY2vtrSzwEaX8BoKzPNkL5pNU3A710b5uj7ZmWzX/XeYhOziG2ptrfJkXrhiv4sOxcrRQxKlDG7OSuiC2EJ4sZsMjl1LMRs5HglsRYO2hGmxViKiO9ZWtbqzE6LuqPKJuuWB+/HIPKRqxDWKc8n0DNw4J0aBQn9IB/CP1Y=
  app: winwintrade
  on:
    repo: yerlandinata/Win-Win-Trade
